# Generated by Django 6.0.3 on 2026-03-05 20:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pawmedicuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawmedicuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
