# Generated by Django 6.0.3 on 2026-03-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='email',
            new_name='user',
        ),
    ]
