# Generated by Django 6.0.3 on 2026-03-27 13:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_pawmedicuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='get_fullname', unique=True),
            preserve_default=False,
        ),
    ]
