# Generated by Django 6.0.3 on 2026-04-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_vetprofile_services_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_vet', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vetprofile')),
            ],
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='favorite_vets',
            field=models.ManyToManyField(related_name='favorite_vets', through='accounts.FavoriteVet', to=settings.AUTH_USER_MODEL),
        ),
    ]
