# Generated by Django 6.0.3 on 2026-04-19 02:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_favoritevet_vetprofile_favorite_vets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vet_photos'),
        ),
    ]
