# Generated by Django 6.0.3 on 2026-03-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('pets', '0003_alter_pet_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets.pet'),
            preserve_default=False,
        ),
    ]
