# Generated by Django 6.0.3 on 2026-03-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='vet',
        ),
    ]
