# Generated by Django 6.0.3 on 2026-03-29 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_owner_appointment_vet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vets', to=settings.AUTH_USER_MODEL),
        ),
    ]
