# Generated by Django 6.0.3 on 2026-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='date_and_time',
            field=models.DateTimeField(default='2026-07-15 14:32:00'),
            preserve_default=False,
        ),
    ]
