# Generated by Django 6.0.3 on 2026-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_pawmedicuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawmedicuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
